<?php
/**
 * Created by PhpStorm.
 * User: Quyet
 * Date: 4/1/2017
 * Time: 12:01 PM
 */

namespace backend\controllers;


use yii\web\Controller;

class BaseController extends Controller
{
    public function beforeAction($action)
    {
        \common\models\MyActiveQuery::$cache_duration = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}