<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Địa chỉ',
    'Body' => 'Nội dung',
    'Contact' => 'Liên hệ',
    'Email' => 'Email',
    'Phone number' => 'Số điện thoại',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'
        => 'Mọi thông tin liên hệ vui lòng điền theo mẫu dưới đây và gửi về hòm thư của chúng tôi. Chúng tôi sẽ phản hồi lại  muộn nhất sau 12h . Xin chân thành cảm ơn!',
    'Name' => 'Họ tên',
    'Subject' => 'Chủ đề',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Cảm ơn bạn đã liên hệ với chúng tôi. Chúng tôi sẽ trả lời sớm nhất có thể.',
    'There was an error sending your message.' => 'Đã có lỗi khi gửi tin nhắn của bạn.',
    'Verification Code' => 'Mã xác thực',
    'Courses and tuition fees' => '@@Khóa học và học phí@@',
    'Documents' => '@@Tài liệu@@',
    'News' => '@@Tin tức@@',
    'Chat with us' => 'Chat với chúng tôi',
    'Home page' => 'Trang chủ',
    'Related articles' => 'Bài viết liên quan',
    'Submit' => 'Gửi đi',
    '{0,number} comments' => '{0,number} bình luận',
    '{0,number} views' => '{0,number} xem',
];
