<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{0,number} comments' => '{0,number} bình luận',
    '{0,number} views' => '{0,number} xem',
    'Courses and tuition fees' => '@@Khóa học và học phí@@',
    'Documents' => '@@Tài liệu@@',
    'News' => '@@Tin tức@@',
    'Chat with us' => 'Chat với chúng tôi',
    'Home page' => 'Trang chủ',
    'Related articles' => 'Bài viết liên quan',
];
