<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/4/2017
 * Time: 12:15 AM
 */

namespace frontend\models;
use \common\models\Image as CommonImage;
class Image extends CommonImage
{
    public function img($size = null, array $options = [])
    {
        return parent::img($size, $options); // TODO: Change the autogenerated stub
    }
}